config/routes.rb
Rails.application.routes.draw do 
  root 'pavers#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/purchase',  to: 'pavers#purchase'
  post '/purchase',  to: 'pavers#purchase_create'
  get  '/purchase_success',  to: 'pavers#purchase_success'
  get  '/purchase_cancel',  to: 'pavers#purchase_cancel'
  get  '/paypal_shim',  to: 'pavers#paypal_shim'
  get '/prompt_for_edit',  to: 'pavers#prompt_for_edit'
  post '/prompt_for_edit',  to: 'pavers#prompt_for_edit'
  resources :users, :pavers
end

app/models/paver.rb
class Paver < ActiveRecord::Base
	validates :Email,  presence: true, length: { maximum: 50 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i } #, :on => :purchase_create
    validates :Paver,  presence: true
    def self.search(search)
    where("Name LIKE ?", "%#{search}%")
    end
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pavers_controller.rb
require "net/http"
require "uri"
class PaversController < ApplicationController
  before_action :set_paver, only: [:show, :edit, :update, :destroy]
  

  # GET /pavers
  # GET /pavers.json
  def index
    @pavers = Paver.all.sort_by{|m| m.Name}
    if params[:search]
        @pavers = Paver.search(params[:search]).order("Name")
        else
        @pavers = Paver.where("Name = 'XYZ'").order("Name")
    end
  end

  # GET /pavers/1
  # GET /pavers/1.json
  def show
  end

  # GET /pavers/new
  def new
    @paver = Paver.new
  end

  # GET /pavers/purcahse
  def purchase
    session[:paver_params] = "empty"  
    @paver = Paver.new
  end

# GET /pavers/purcahse_create
  def purchase_create
    @paver = Paver.new(paver_params)
    #debugger
    if @paver.valid?()
      session[:paver_params] = paver_params  
      if Rails.env.development?   
        if @paver[Paver] == "4x8"
          redirect_to action: "paypal_shim"
        elsif @paver[Paver] == "8x8-4"
          redirect_to action: "paypal_shim"
        elsif @paver[Paver] == "8x8-5"      
          redirect_to action: "paypal_shim"
        else
          render :purchase
        end
      else
        if @paver[Paver] == "4x8"
          redirect_to "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GYHB5J5EVGEK2"  
        elsif @paver[Paver] == "8x8-4"
          redirect_to "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=T6KKJZ6MVMN7C"
         elsif @paver[Paver] == "8x8-5"   
          redirect_to "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=JB9F49XD5Z2NC"
        else
          render :purchase
        end
      end
    else
      render :purchase
    end  
  end

  def paypal_shim
     #render :text => "paypal_shim"
  end


  def purchase_success
    @paver = Paver.new(session[:paver_params])

    respond_to do |format|
      if @paver.save
        format.html { redirect_to @paver, notice: 'Paver was successfully created.' }
        format.json { render :show, status: :created, location: @paver }
      else
        format.html { render :new }
        format.json { render json: @paver.errors, status: :unprocessable_entity }
      end
    end
  end

  def purchase_cancel
    flash[:notice] = "Paver was was Canceled."
    redirect_to root_path
  end

  def prompt_for_edit
    #debugger
    current = Paver.find(params[:format]) 
    if (current.Email.downcase == params[:Email_Prompt].downcase)
      redirect_to edit_paver_path(params[:format])
    else
      #redirect_to show_paver_path(params[:format])
      flash[:notice] = "Paver: Incorrect Email entered to enable Editing."
      redirect_to paver_path(params[:format])
    end
  end

  # GET /pavers/1/edit
  def edit 
  end

  # POST /pavers
  # POST /pavers.json
  def create
    @paver = Paver.new(paver_params)
    #debugger
    respond_to do |format|
      if @paver.save
        format.html { redirect_to @paver, notice: 'Paver was successfully created.' }
        format.json { render :show, status: :created, location: @paver }
      else
        format.html { render :new }
        format.json { render json: @paver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pavers/1
  # PATCH/PUT /pavers/1.json
  def update
    respond_to do |format|
      if @paver.update(paver_params)
        format.html { redirect_to @paver, notice: 'Paver was successfully updated.' }
        format.json { render :show, status: :ok, location: @paver }
      else
        format.html { render :edit }
        format.json { render json: @paver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pavers/1
  # DELETE /pavers/1.json
  def destroy
    @paver.destroy
    respond_to do |format|
      format.html { redirect_to pavers_url, notice: 'Paver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paver
      @paver = Paver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paver_params
      params.require(:paver).permit(:Name, :Logo, :Line1, :Line2, :Line3, :Line4, :Line5, :Paver, :Placement, :Row, :Col,
                                    :Install_Date, :Purchaser, :Email, :PayPal_ID, :Email_Prompt)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
     log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    #debugger
  end

  def new
  	@user = User.new
  end

  def create
    
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Loged in as Admin!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_form_builder.rb
class MyFormBuilder < ActionView::Helpers::FormBuilder

  def text_field(attribute, options={})
    @template.content_tag(:div, class: "field") do
      label(attribute) +
      super
    end
  end

  def date_select(attribute, options={})
    @template.content_tag(:div, class: "field") do
      label(attribute) +
      super
    end
  end

  def text_area(attribute, options={})
    @template.content_tag(:div, class: "field") do
      label(attribute) +
      super
    end
  end

  def check_box(attribute, options={})
    @template.content_tag(:div, class: "field") do
      label(attribute) +
      super
    end
  end

  def submit(options={})
    @template.content_tag(:div, class: "actions") do
      super
    end
  end

end

app/helpers/pavers_helper.rb
module PaversHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

   # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<style type="text/css">
   body { background-image: linear-gradient(90deg, #FFFFFF, #1a53ff); !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */

</style>
<head>
  <title>Paver</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :js %>
  <%= csrf_meta_tags %>
</head>
<body class="foo_me">
<div class="container">
	<% flash.each do |message_type, message| %>
		<% if !message.include?("Paver") %>
	        <div class="alert alert-<%= message_type %>"><%= message %></div>
	    <% end %>
	<% end %>
	<%= yield %>
	<% if request.original_url().include?("localhost")  %>
	<%= debug(params) if Rails.env.development? %>
	<%= debug session[:paver_params] if Rails.env.development? %>
<!-- 	<%= debug session if Rails.env.development? %>-->
	<% end %>
</div>
</body>
</html>

app/views/pavers/_form.html.erb
<% if false %>
<%= form_for(@paver, builder: MyFormBuilder) do |f| %>
  <%= f.text_field :Name %>
  <%= f.submit %>
<% end %>
<% end %>

<%= form_for(@paver) do |f| %>
  <% if @paver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paver.errors.count, "error") %> prohibited this paver from being saved:</h2>

      <ul>
      <% @paver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group container", style="padding-left: 15px;">
  <div style="float:left;">
  <%= image_tag "4x8.jpg" %>  <br />
  <%= f.radio_button :Paver, '4x8', :class => "paver_radio", disabled: !logged_in? %> 4" x 8" (3 text lines) $50 
  </div>
  <div style="float:left;padding-left: 30px;">
  <%= image_tag "8x8-4.jpg" %>  <br />
  <%= f.radio_button :Paver, '8x8-4', :class => "paver_radio", disabled: !logged_in? %> 8" x 8" (1 Logo + 4 text lines) $100 
  </div>
   <div style="float:left;padding-left: 30px;">
  <%= image_tag "8x8-5.jpg" %>  <br />
  <%= f.radio_button :Paver, '8x8-5', :class => "paver_radio", disabled: !logged_in? %> 8" x 8" (5 text lines) $100 
  </div>
  </div>

  
  
  <div class="form-group", style="padding-left: 15px;">
  <%= f.label :Purchaser, "Purchaser Name ( e.g. Robert Smith )", class: "control-label" %>
  <%= f.text_field :Purchaser, :size => 50, :maxlength => 50 %>   
 </div>

  <div class="form-group", style="padding-left: 15px;">
  <%= f.label :Name, "Deceased Name ( e.g. James Smith )", class: "control-label" %>
  <%= f.text_field :Name, :size => 51, :maxlength => 51 %>   
 </div>
 
 <div class="form-group", style="padding-left: 15px;">
  <%= f.label :Placement, class: "control-label" %>
  <%= f.select :Placement,
        [['WWI','WWI'],['WWII','WWII'],['Korea','Korea'],['Vietnam','Vietnam'],
        ['Gulf War','Gulf War'],['Iraq','Iraq'],['Afghanistan','Afghanistan'],
        ['Purple Heart','Purple Heart'],['Women in Service','Women in Service'],['POW/MIA','POW/MIA']],
        class: "form-control"  %> 
  </div>
 

  <div id="Logo" class="form-group", style="padding-left: 15px; id=Logo">
    <%= f.label :Logo, class: "control-label" %>
    <%= f.select :Logo,
          [['None','None'],['Army','Army'],['Marine Corp','Marine Corp'],['Navy','Navy'],
          ['Air Force','Air Force'],['Coast Guard','Coast Guard']],
          class: "form-control" %>
  </div>

  <%= render :partial => "my_field_format", :locals=>{:f => f, :fn => "Line1", :rws =>  1,  :sample_txt => "In Memory Of"} %> 
  <%= render :partial => "my_field_format", :locals=>{:f => f, :fn => "Line2", :rws => 1, :sample_txt => "Lt. James F. Smith"} %>  
  <%= render :partial => "my_field_format", :locals=>{:f => f, :fn => "Line3", :rws => 1, :sample_txt => "US Marine Corps"} %> 
  <%= render :partial => "my_field_format", :locals=>{:f => f, :fn => "Line4", :rws => 1, :sample_txt => "Vietnam 1969-1970"} %> 
  <%= render :partial => "my_field_format", :locals=>{:f => f, :fn => "Line5", :rws => 1, :sample_txt => "Atlanta GA"} %> 
  <%= render :partial => "my_field_format", :locals=>{:f => f, :fn => "Row", :rws => 1, :sample_txt => "Row 4"} %> 
  <%= render :partial => "my_field_format", :locals=>{:f => f, :fn => "Col", :rws => 1, :sample_txt => "Column B"} %> 
  
  <% if logged_in? %>
  <div id=logged_in class="form-group", style="padding-left: 15px;"><br /><br />
   <!--  <%= f.label :PayPal_ID, class: "control-label" %> -->
   <!--  <%= f.text_field :PayPal_ID, :size => 20, :maxlength => 20 %>    -->
    <%= f.label :Email, class: "control-label" %>
    <%= f.text_field :Email, :size => 30, :maxlength => 30 %>  
    <%= f.label :Install_Date, class: "control-label" %>
    <%= f.text_field :Install_Date, :size => 10, :maxlength => 10 %>   
  </div>
  <% else %>
    <br /><br />
  <% end %>

  <div class="actions">
    <%= f.submit "Save Changes" ,:class => "btn btn-default btn-sm" %>
    <%= link_to 'Cancel Changes', @paver, :class => "btn btn-info btn-sm" %> 
    <%= link_to 'Back to Search', pavers_path, :class => "btn btn-info btn-sm" %>
  </div>
<% end %>

app/views/pavers/_my_field_format.html.erb
<div id="<%=fn%>" class="form-group">
    <%= f.label fn, class: "col-md-1 control-label" %>
    ( e.g. "<%= sample_txt %>" )
    <div class="col-md-12">
      <%= f.text_field fn, :size => 40, :maxlength => 18 %>   
      <br /> 
    </div>
</div>

app/views/pavers/edit.html.erb
<h1>Editing Paver</h1>

<%= render 'form' %>

app/views/pavers/index.html.erb
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

<p id="notice"><%= notice %></p>

<style>
.google-maps {
        position: relative;
        padding-bottom: 40%; // This is the aspect ratio
        height: 0;
        overflow: hidden;
    }
    .google-maps iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100% !important;
        height: 100% !important;
    }
</style>

<!-- 
<div class="row">
  <div class="col-md-6">
    <img style="background: transparent;" src="veterans.jpeg" class="img-thumbnail" alt="Veterans Image" width="604" height="200">
  </div>
    <div class="col-md-6">
    <div class="google-maps">
      <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3805.474821790624!2d-77.0455412!3d38.8890473!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e1!3m2!1sen!2sus!4v1466204205129" width="550" height="210" frameborder="0" style="border:0" allowfullscreen>
      </iframe>
    </div>
  </div>
</div>
 -->
<br>

 
 
 <div style="float:left;"> 
  <%= button_to "Purchase Paver", purchase_path, :id => "purchase-dailog-btn",
        :class => "btn btn-success btn-sm", :method => :get %>

</div> 

<% if !logged_in? %>
<div style="float:right;">
  <%= button_to "Admin Login", login_path, :id => "admin-dailog-btn",
        :class => "btn btn-default btn-sm", :method => :get %>
</div> 
<% else %>
<div style="float:right;">
  <%= button_to "Logout", {:controller => :sessions, :action => 'destroy', :id => "admin-dailog-btn"},
         :method => :delete, :class => "btn btn-default btn-sm" %>
</div> 
<% end %> 
<%= form_tag(pavers_path, :method => "get", id: "search-form") do %>
<%= label_tag(:q, " ", :style=>'width:50px;') %> 
<%= label_tag(:q, "   Enter the First or Last Name:") %>
<%= text_field_tag :search, params[:search], placeholder: "Search Pavers" %>


<%= button_tag(type: "submit", class: "new_post_submit") do %>
  <span><i class="glyphicon glyphicon-search"></i> Search</span>
<% end %> 

<!-- 
<a href="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjgioHGnLLNAhUURGMKHfI8BC4QFggcMAA&url=http%3A%2F%2Fwww.johnscreekga.gov%2FParksAndRecreation%2FSeniors%2FJohns-Creek-Veterans-Association.aspx&usg=AFQjCNGqUGrHhqhxJbKBkZFrau78T0rIDw&sig2=8OJwz-ZbEON_xTmyfBj32w&bvm=bv.124817099,d.cGc">Visit Johns Creek Veterans Association WebSite</a>
<a href="http://www.facebook.com/johnscreekgagov"><span class="fa fa-fw fa-facebook"</span></a>
<a href="http://www.twitter.com/johnscreekgagov"><span class="fa fa-twitter"</span></a>
 -->
<% end %>


<br>
<div class="bg-success">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Logo</th>
      <th>Line1</th>
      <th>Line2</th>
      <th>Line3</th>
      <th>Line4</th>
      <th>Line5</th>
      <th>Paver</th>
      <th>Placement</th>
      <th>Row</th>
      <th>Col</th>
      <th></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @pavers.each do |paver| %>
      <tr>
        <td><%= paver.Name %></td>
        <td><%= paver.Logo %></td>
        <td><%= paver.Line1 %></td>
        <td><%= paver.Line2 %></td>
        <td><%= paver.Line3 %></td>
        <td><%= paver.Line4 %></td>
        <td><%= paver.Line5 %></td>
        <td><%= paver.Paver %></td>
        <td><%= paver.Placement %></td>
        <td><%= paver.Row %></td>
        <td><%= paver.Col %></td>
        <td><%= link_to 'Details', paver %></td>
  <!--       <td><%= link_to 'Edit', edit_paver_path(paver) %></td> -->
  <!--       <td><%= link_to 'Destroy', paver, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>
 <% if logged_in? %>
  <%= link_to 'New Paver', new_paver_path %>
 <% end %> 
</div>
<br><br><br>

app/views/pavers/new.html.erb
<h1>New Paver</h1>
<%= render 'form' %>
<%= link_to 'Back', pavers_path %>

app/views/pavers/paypal_shim.html.erb
Mock PayPal Page
<%= link_to "Accept", purchase_success_path %>
<%= link_to "Cancel", purchase_cancel_path %>

app/views/pavers/purchase.html.erb
<% content_for :js do %>
  <script>
   $(".foo_me").click(function() {
  alert("only runs on the contact page!")
})

  </script>
<% end %>

<h1>Purchase Paver</h1>
<%= render 'purchase' %>
<div style="float:left;"> 
  <%= button_to "Cancel", root_path, :id => "purchase-dailog-btn",
        :class => "btn btn-warning btn-sm", :method => :get %>

</div> 

app/views/pavers/show.html.erb
<p id="notice"><%= notice %></p>
<style>
div.wrapperx{
    float:left; /* important */
    position:relative; /* important(so we can absolutely position the description div */
}
div.descriptionx{
    position:absolute; /* absolute position (so we can position it where we want)*/
    top:calc(30% - 24px); /* position will be on bottom */
    left:10px;
    text-align: center;
    width:100%;
    /* styling bellow */
    background-color:transparent;
    font-family: 'tahoma';
    /*font-size:15px;*/
    color:black;
    opacity:0.9; /* transparency */
    filter:alpha(opacity=60); /* IE transparency */
    line-height: .5;
}
div.descriptionx2{
    position:absolute; /* absolute position (so we can position it where we want)*/
    top:calc(20% - 24px); /* position will be on bottom */
    left:1px;
    text-align: center;
    width:100%;
    /* styling bellow */
    background-color:transparent;
    font-family: 'tahoma';
    /*font-size:15px;*/
    color:black;
    opacity:0.9; /* transparency */
    filter:alpha(opacity=60); /* IE transparency */
    line-height: .5;
}
p.description_contentx{
    text-shadow: 0px 1px 0px rgba(255,255,255,.5);
    padding:2px;
    margin:0px;
}

h2.description_contenty{
    font-size: 4.0vh; 
    text-shadow: 0px 1px 0px rgba(255,255,255,.5);
    padding:2px;
    margin:0px;
}
</style>

<div class="container">
<div class='wrapperx'>
<div class="img-rounded" >
    <% if @paver.Paver == "4x8" %>
    <img class="img-responsive" src="../brick.jpg" width="600" border="0"/>
    <div class='descriptionx'>
   <% else %>
    <img class="img-responsive" src="../brick8x8.jpg" width="600" border="0"/>
    <div class='descriptionx2'>
   <% end %> 
     <% if @paver.Paver == "8x8-4" %>
     <center><img class="img-responsive" width="177" src="../navy.jpg" style="margin-bottom: 20px;" /></center>
     <% end %> 
     <h2 class='description_contenty'> <%= @paver.Line1 %> </h2>
     <h2 class='description_contenty'> <%= @paver.Line2 %> </h2>
     <h2 class='description_contenty'> <%= @paver.Line3 %> </h2>
     <h2 class='description_contenty'> <%= @paver.Line4 %> </h2>
     <h2 class='description_contenty'> <%= @paver.Line5 %> </h2>
    <!--  <h2 class='description_contenty'> Paver: <%= @paver.Paver %> </h2> -->
   <!--   <h2 class='description_contenty'> Placement: <%= @paver.Placement %> </h2> -->
   <!--   <h2 class='description_contenty'> Row: <%= @paver.Row %> </h2> -->
   <!--   <h2 class='description_contenty'> Col: <%= @paver.Col %> </h2> -->
</div>
</div>
</div>

<div class="container", style="padding-top: 20px; float:left; /* important */">
<% if logged_in? %> 
    <%= link_to 'Edit Paver', edit_paver_path(@paver), :class => "btn btn-default btn-md" %>
    <%= link_to "Back to Search", pavers_path, :class => "btn btn-info btn-md" %>
<% else %>
  <%= form_for(@paver, url: prompt_for_edit_path(@paver), :method => :POST) do |f| %>
    <%= label_tag 'Enter Email Adress to Edit' %>    
    <%= text_field_tag "Email_Prompt", '', size: 50 %>
    <%= f.submit "Edit Paver", :class => "btn btn-default btn-sm" %>
    <%= link_to "Back to Search", pavers_path, :class => "btn btn-info btn-sm" %>
    <% end  %>
<% end -%> 
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation2">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control col-md-2' %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control col-md-2'  %>
      </div>

      <div class="form-group">
       <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control col-md-2' %>
      </div>

      <div class="form-group">
       <%= f.label :password_confirmation, "Confirm" %>
       <%= f.password_field :password_confirmation, class: 'form-control col-md-2' %>
      </div>
      
      <div class="form-group">
       <%= f.submit "Create my account", class: "btn btn-primary" %>
      </div>
    <% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>